### ISSUE TITLE
Use anteater icon for document icon

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#47]
Is this something that can be rendered by the system? If not, let me know and I'll throw something together in Photoshop or Sketch. Does Apple publish a document icon template?

**Comment by keith** [comment]
So it looks like if I set this on my machine I get the icon if I "get info" on the file, but I don't see it on the desktop since QuickLook happily shows me the JSON from the file instead.

I removed my QuickLook plugins to see if those were the cause, but it doesn't seem so. I'm going to add this like this for now and see how it goes.

**Comment by keith** [comment]
Done in https://github.com/br1sk/brisk/pull/83
